apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s*
build:
  local:
    push: false
  artifacts:
    - image: billycatchpole/auth
      context: .
      docker:
        dockerfile: services/auth/Dockerfile
      sync:
        manual:
          - src: "services/auth/src/**/*.ts"
            dest: .
