apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealplan-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealplan
  template:
    metadata:
      labels:
        app: mealplan
    spec:
      containers:
        - name: mealplan
          image: billycatchpole/mealplan
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-uri
                  key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: mealplan-srv
spec:
  type: ClusterIP
  selector:
    app: mealplan
  ports:
    - name: mealplan
      protocol: TCP
      port: 3000
      targetPort: 3000
