name: 'an-app'

on:
  push:
    branches: [master]
    paths:
      - 'apps/an-app/**'
      - '.github/workflow/an-app.yaml'
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    defaults:
      run:
        working-directory: ./apps/an-app

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        working-directory: ./apps/an-app
        run: yarn build
      - name: Test
        working-directory: ./apps/an-app
        run: yarn test
