name: auth-service

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    defaults:
      run:
        working-directory: ./services/auth

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker build -t billycatchpole/auth ../../ -f Dockerfile
