name: Deploy web client
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'apps/web-client/**'

permissions:
  id-token: write
  contents: write

jobs:
  deploy-to-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18' 
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --scope=web-client

      - name: build web client
        run: yarn build --scope=web-client

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist/ s3://${{ secrets.AWS_BUCKET_NAME }} --delete



