name: Product Catalogue - Publish OpenAPI Package

on:
  push:
    branches:
      - master
    paths:
      - 'services/product-catalogue/VERSION'

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
    
      - uses: actions/setup-node@v4
        with:
          node-version: '18' 
    
      - name: Generate OpenAPI package
        run: npm run generate-open-api-package
        working-directory: ./services/product-catalogue

      - name: Get version from VERSION file
        id: version
        run: echo "::set-output name=VERSION::$(cat ./services/product-catalogue/VERSION)"
      
      - name: Bump package version
        run: npm version ${{ steps.version.outputs.VERSION }} --no-git-tag-version
        working-directory: ./packages/api/product-catalogue
      
      - name: Publish package to npm
        run: npm publish
        working-directory: ./packages/api/product-catalogue
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
