name: tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: yarn install --frozen-lockfile 

      - name: build everything
        run: yarn turbo run build

      - name: test affected code
        run: npx turbo run test-affected-packages
